### ISSUE TITLE
Display function body 

### ISSUE THREAD

**Issue by slavaGanzin** [n-riesco/jp-coffeescript#3]
I recently switched to your kernel from notablemind's one. 
And what I miss for is displaying body of function. I think this is by design but why?

```
jupyter-nodejs:
> a = -> a
> a
function a ( ) {
return a;
}
```

and not just [Function a] which is more expected by design of javascript, but meaningless a bit too.

**Comment by n-riesco** [comment]
It is how `util.inspect` outputs a function. You can get the other output by calling `.toString()` instead, e.g.:

In[1]: a = -> a
Out[1]: [Function]
In[2]: a.toString()
Out[2]: 'function () {\n  return a;\n}'
