### ISSUE TITLE
jp-coffee-install unable to find js-green-32x32.png

### ISSUE THREAD

**Issue by awkwong-whi** [n-riesco/jp-coffeescript#8]
I have a fresh install of node.js (v6.10.2) installed to `/usr/local/lib64/node-v6.10.2-linux-x64` and symlinks for node and npm in `/usr/local/bin`.
I also did a `npm -g install jp-coffeescript` as root and also did an `npm -g update` to ensure all packages were up to date.
After the installation, I added symlinks for the new jp-coffee commands into `/usr/local/bin` and ran `jp-coffee-install` but received the following error:

```
[user@ec2-inst1 ~]$ jp-coffee-install
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib64/node-v6.10.2-linux-x64/lib/node_modules/jp-coffeescript/images/nodejs/js-green-32x32.png'
    at Error (native)
```

**Comment by n-riesco** [comment]
I was told once that `npm update` doesn't work with global packages. I don't know if this is still the case, but I recommend instead:

```sh
$ npm uninstall -g jp-coffeescript
$ npm install -g jp-coffeescript
```

**Comment by n-riesco** [comment]
Don't mind my previous comment. This is actually a bug in the package. It's missing Node's logo. I'll fix this today.
