### ISSUE TITLE
variables not saved between cells 

### ISSUE THREAD

**Issue by danlaudk** [n-riesco/jp-coffeescript#9]
the coffeescript notebook does not seem able to save variables that were run in one cell, to be used in another cell? 

![jupyter with 2lines on js kernel, 2 lines on coffeescript kernel](https://user-images.githubusercontent.com/7819654/27988961-640f9f30-63e3-11e7-8d22-37760e200d50.png)

$npm version
ip{ npm: '4.2.0',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.10.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.43',
  zlib: '1.2.11' }

$ ipython --version
lsb5.4.1

$ jupyter --version
4.3.0

$ lsb_release -sd
Ubuntu 14.04.5 LTS

$ jp-coffee-install --versions
jp-coffeescript 1.0.2
jmp 0.7.5
jp-kernel 0.1.3
nel 0.5.3
uuid 3.1.0
zeromq 4.5.0

**Comment by n-riesco** [comment]
@danlaudk Thank you for your report! It's shocking for how long this issue has gone unreported.

I've just published a fix in jp-coffescript@1.0.3.
